# Generated by Django 4.1.7 on 2023-03-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.CharField(max_length=200)),
                ('start_time', models.CharField(max_length=200)),
                ('mtg_format', models.CharField(max_length=200)),
                ('entry', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('departure', models.CharField(max_length=200)),
                ('return_date', models.CharField(max_length=200)),
            ],
        ),
    ]
