# Generated by Django 4.1.7 on 2023-03-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_name', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('license_plate_number', models.CharField(max_length=200)),
                ('seats', models.CharField(max_length=200)),
                ('trunk_available', models.CharField(max_length=200)),
                ('smoking', models.CharField(max_length=200)),
            ],
        ),
    ]
