# Generated by Django 4.1.7 on 2023-03-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='public_name',
            field=models.CharField(default='car', max_length=200),
            preserve_default=False,
        ),
    ]
