# Generated by Django 4.1.7 on 2023-03-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_voyager_vehicle_public_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
            ],
        ),
    ]
