# Generated by Django 4.1.7 on 2023-03-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0005_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyager',
            name='first',
            field=models.CharField(default='no', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voyager',
            name='last_name',
            field=models.CharField(default='no', max_length=200),
            preserve_default=False,
        ),
    ]
