# Generated by Django 4.1.7 on 2023-03-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0006_voyager_first_voyager_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyager',
            old_name='first',
            new_name='first_name',
        ),
    ]
