# Generated by Django 4.1.7 on 2023-03-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0007_rename_first_voyager_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyager',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='voyager',
            name='last_name',
        ),
    ]
