# Generated by Django 4.1.7 on 2023-03-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0008_remove_voyager_first_name_remove_voyager_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyager',
            name='first_name',
            field=models.CharField(default='anthony', max_length=200),
            preserve_default=False,
        ),
    ]
