# Generated by Django 4.1.7 on 2023-03-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0009_voyager_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyager',
            name='last_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
